import { app, BrowserWindow, shell } from 'electron';
import path from 'node:path';

import { CodexAppServerClient } from './codex-subscription/client';
import { registerCodexSubscriptionIpc } from './codex-subscription/ipc';
import {
  buildCodexEnvironment,
  prepareCodexHome,
  resolveCodexRuntimePath,
  verifyCodexRuntimeVersion,
} from './codex-subscription/runtime';
import { CodexSubscriptionService } from './codex-subscription/service';
import { registerMaterialIpc } from './media/ipc';
import { registerMaterialProtocol } from './media/protocol';
import { MaterialSessionService } from './media/session';
import { registerModelIpc } from './model/ipc';
import {
  createCustomOpenAiCompatibleProvider,
  createDeepSeekProvider,
  createOpenAiProvider,
} from './model/provider';
import { ModelProviderRegistry } from './model/registry';
import { ModelService } from './model/service';
import { ElectronSafeStorageCipher, ModelCredentialVault } from './model/vault';
import { registerProductIpc, registerUnavailableProductIpc } from './product/ipc';
import { ProductRepository } from './product/repository';
import { registerRecordIpc, registerUnavailableRecordIpc } from './record/ipc';
import { RecordRepository } from './record/repository';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

let productRepository: ProductRepository | null = null;
let recordRepository: RecordRepository | null = null;
let codexSubscriptionService: CodexSubscriptionService | null = null;
let unregisterCodexSubscriptionIpc: (() => void) | null = null;
let mainWindow: BrowserWindow | null = null;
const materialSessionService = new MaterialSessionService();

const createWindow = (): void => {
  const window = new BrowserWindow({
    backgroundColor: '#f3f6fb',
    height: 900,
    minHeight: 720,
    minWidth: 1120,
    title: 'Material 素材分析',
    width: 1440,
    webPreferences: {
      contextIsolation: true,
      nodeIntegration: false,
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      sandbox: true,
    },
  });

  mainWindow = window;
  window.on('closed', () => {
    if (mainWindow === window) mainWindow = null;
  });
  window.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(async () => {
  registerMaterialProtocol(materialSessionService);
  registerMaterialIpc(materialSessionService);
  const modelRegistry = new ModelProviderRegistry();
  modelRegistry.register(createOpenAiProvider());
  modelRegistry.register(createDeepSeekProvider());
  modelRegistry.register(createCustomOpenAiCompatibleProvider());
  const modelVault = new ModelCredentialVault(
    path.join(app.getPath('userData'), 'model-credentials.secure.json'),
    new ElectronSafeStorageCipher(),
  );
  const modelService = new ModelService(modelRegistry, modelVault);
  const databasePath = path.join(app.getPath('userData'), 'material-products.sqlite3');
  const backupDirectory = path.join(app.getPath('userData'), 'backups', 'products');
  try {
    productRepository = new ProductRepository(databasePath, backupDirectory);
    registerProductIpc(productRepository);
  } catch {
    registerUnavailableProductIpc('产品库无法打开，请检查应用数据目录权限或数据库版本');
  }
  const recordDatabasePath = path.join(
    app.getPath('userData'),
    'material-analysis-records.sqlite3',
  );
  try {
    recordRepository = new RecordRepository(recordDatabasePath);
    registerRecordIpc(recordRepository);
  } catch {
    registerUnavailableRecordIpc('分析记录无法打开，请检查应用数据目录权限或数据库版本');
  }
  registerModelIpc(
    modelService,
    (webContentsId) => BrowserWindow.getAllWindows().some(
      (window) => window.webContents.id === webContentsId,
    ),
  );
  const codexDataDirectory = path.join(app.getPath('userData'), 'codex-subscription');
  const createCodexClient = async (): Promise<CodexAppServerClient> => {
    const command = await resolveCodexRuntimePath({
      isPackaged: app.isPackaged,
      resourcesPath: process.resourcesPath,
    });
    const codexHome = await prepareCodexHome(
      path.join(codexDataDirectory, 'codex-home'),
    );
    const environment = buildCodexEnvironment(codexHome);
    await verifyCodexRuntimeVersion({ codexHome, command, environment });
    return new CodexAppServerClient({
      appVersion: app.getVersion(),
      codexHome,
      command,
      environment,
    });
  };
  codexSubscriptionService = new CodexSubscriptionService({
    client: null,
    clientFactory: createCodexClient,
    openExternal: (url) => shell.openExternal(url),
    settingsPath: path.join(codexDataDirectory, 'settings.json'),
  });
  unregisterCodexSubscriptionIpc = registerCodexSubscriptionIpc(
    codexSubscriptionService,
    (webContentsId) => mainWindow !== null
      && !mainWindow.isDestroyed()
      && mainWindow.webContents.id === webContentsId,
    (channel, payload) => {
      if (mainWindow && !mainWindow.isDestroyed() && !mainWindow.webContents.isDestroyed()) {
        mainWindow.webContents.send(channel, payload);
      }
    },
  );
  createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (!mainWindow || mainWindow.isDestroyed()) {
    createWindow();
  }
});

app.on('before-quit', () => {
  unregisterCodexSubscriptionIpc?.();
  unregisterCodexSubscriptionIpc = null;
  codexSubscriptionService?.stop();
  codexSubscriptionService = null;
  materialSessionService.clear();
  productRepository?.close();
  productRepository = null;
  recordRepository?.close();
  recordRepository = null;
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
