import { app, BrowserWindow } from 'electron';
import path from 'node:path';

import { registerMaterialIpc } from './media/ipc';
import { registerMaterialProtocol } from './media/protocol';
import { MaterialSessionService } from './media/session';
import { registerProductIpc, registerUnavailableProductIpc } from './product/ipc';
import { ProductRepository } from './product/repository';
import { registerRecordIpc, registerUnavailableRecordIpc } from './record/ipc';
import { RecordRepository } from './record/repository';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

let productRepository: ProductRepository | null = null;
let recordRepository: RecordRepository | null = null;
const materialSessionService = new MaterialSessionService();

const createWindow = (): void => {
  const mainWindow = new BrowserWindow({
    backgroundColor: '#f3f6fb',
    height: 900,
    minHeight: 720,
    minWidth: 1120,
    title: 'Material 素材分析',
    width: 1440,
    webPreferences: {
      contextIsolation: true,
      nodeIntegration: false,
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      sandbox: true,
    },
  });

  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(() => {
  registerMaterialProtocol(materialSessionService);
  registerMaterialIpc(materialSessionService);
  const databasePath = path.join(app.getPath('userData'), 'material-products.sqlite3');
  const backupDirectory = path.join(app.getPath('userData'), 'backups', 'products');
  try {
    productRepository = new ProductRepository(databasePath, backupDirectory);
    registerProductIpc(productRepository);
  } catch {
    registerUnavailableProductIpc('产品库无法打开，请检查应用数据目录权限或数据库版本');
  }
  const recordDatabasePath = path.join(
    app.getPath('userData'),
    'material-analysis-records.sqlite3',
  );
  try {
    recordRepository = new RecordRepository(recordDatabasePath);
    registerRecordIpc(recordRepository);
  } catch {
    registerUnavailableRecordIpc('分析记录无法打开，请检查应用数据目录权限或数据库版本');
  }
  createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

app.on('before-quit', () => {
  materialSessionService.clear();
  productRepository?.close();
  productRepository = null;
  recordRepository?.close();
  recordRepository = null;
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
