import { app, BrowserWindow, shell } from 'electron';
import path from 'node:path';

import { AnalysisEngine } from './analysis-engine';
import {
  AnalysisRuntimeService,
  registerAnalysisRuntimeIpc,
} from './analysis-runtime';
import { CodexAppServerClient } from './codex-subscription/client';
import { registerCodexSubscriptionIpc } from './codex-subscription/ipc';
import { isTrustedMainWindowSender } from './codex-subscription/ipc-trust';
import { CodexSubscriptionModelRouter } from './codex-subscription/model-router';
import {
  buildCodexEnvironment,
  EXPECTED_CODEX_RUNTIME_VERSION,
  prepareCodexHome,
  resolveCodexRuntimePath,
  verifyCodexRuntimeVersion,
} from './codex-subscription/runtime';
import { CodexSubscriptionService } from './codex-subscription/service';
import { registerMaterialIpc } from './media/ipc';
import { registerMaterialProtocol } from './media/protocol';
import { MaterialSessionService } from './media/session';
import {
  materialSessionSourceResolver,
  registerDeterministicMediaTools,
} from './media-tools';
import { registerModelIpc } from './model/ipc';
import {
  createCustomOpenAiCompatibleProvider,
  createDeepSeekProvider,
  createOpenAiProvider,
} from './model/provider';
import { ModelProviderRegistry } from './model/registry';
import { ModelService } from './model/service';
import { ElectronSafeStorageCipher, ModelCredentialVault } from './model/vault';
import { registerProductIpc, registerUnavailableProductIpc } from './product/ipc';
import { ProductRepository } from './product/repository';
import { registerRecordIpc, registerUnavailableRecordIpc } from './record/ipc';
import { ElectronRecordPdfExporter } from './record/pdf-exporter';
import { RecordRepository } from './record/repository';
import {
  ElectronRecordSourceCipher,
  RecordSourceAccessService,
} from './record/source-access';
import {
  TemporaryArtifactManager,
  ToolBroker,
  ToolRegistry,
} from './tooling';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

let productRepository: ProductRepository | null = null;
let recordRepository: RecordRepository | null = null;
let analysisRuntimeService: AnalysisRuntimeService | null = null;
let codexSubscriptionService: CodexSubscriptionService | null = null;
let unregisterCodexSubscriptionIpc: (() => void) | null = null;
let mainWindow: BrowserWindow | null = null;
const materialSessionService = new MaterialSessionService();
const isTrustedSender = (webContentsId: number): boolean =>
  isTrustedMainWindowSender(mainWindow, webContentsId);

const createWindow = (): void => {
  const window = new BrowserWindow({
    backgroundColor: '#f3f6fb',
    height: 900,
    minHeight: 720,
    minWidth: 1120,
    title: 'Material 素材分析',
    width: 1440,
    webPreferences: {
      contextIsolation: true,
      nodeIntegration: false,
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      sandbox: true,
    },
  });

  mainWindow = window;
  window.on('closed', () => {
    if (mainWindow === window) mainWindow = null;
  });
  window.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(() => {
  registerMaterialProtocol(materialSessionService);
  registerMaterialIpc(materialSessionService);
  const modelRegistry = new ModelProviderRegistry();
  modelRegistry.register(createOpenAiProvider());
  modelRegistry.register(createDeepSeekProvider());
  modelRegistry.register(createCustomOpenAiCompatibleProvider());
  const modelVault = new ModelCredentialVault(
    path.join(app.getPath('userData'), 'model-credentials.secure.json'),
    new ElectronSafeStorageCipher(),
  );
  const modelService = new ModelService(modelRegistry, modelVault);
  const codexDataDirectory = path.join(app.getPath('userData'), 'codex-subscription');
  const createCodexClient = async (): Promise<CodexAppServerClient> => {
    const command = await resolveCodexRuntimePath({
      isPackaged: app.isPackaged,
      resourcesPath: process.resourcesPath,
    });
    const codexHome = await prepareCodexHome(
      path.join(codexDataDirectory, `codex-home-v${EXPECTED_CODEX_RUNTIME_VERSION}`),
    );
    const environment = buildCodexEnvironment(codexHome);
    await verifyCodexRuntimeVersion({ codexHome, command, environment });
    return new CodexAppServerClient({
      appVersion: app.getVersion(),
      codexHome,
      command,
      environment,
    });
  };
  codexSubscriptionService = new CodexSubscriptionService({
    client: null,
    clientFactory: createCodexClient,
    openExternal: (url) => shell.openExternal(url),
    settingsPath: path.join(codexDataDirectory, 'settings.json'),
  });
  const databasePath = path.join(app.getPath('userData'), 'material-products.sqlite3');
  const backupDirectory = path.join(app.getPath('userData'), 'backups', 'products');
  try {
    productRepository = new ProductRepository(databasePath, backupDirectory);
    registerProductIpc(productRepository);
  } catch {
    registerUnavailableProductIpc('产品库无法打开，请检查应用数据目录权限或数据库版本');
  }
  const recordDatabasePath = path.join(
    app.getPath('userData'),
    'material-analysis-records.sqlite3',
  );
  const recordBackupDirectory = path.join(
    app.getPath('userData'),
    'backups',
    'records',
  );
  try {
    recordRepository = new RecordRepository(recordDatabasePath, recordBackupDirectory);
    registerRecordIpc(
      recordRepository,
      isTrustedSender,
      new ElectronRecordPdfExporter(),
      new RecordSourceAccessService(
        materialSessionService,
        new ElectronRecordSourceCipher(),
      ),
    );
  } catch {
    registerUnavailableRecordIpc('分析记录无法打开，请检查应用数据目录权限或数据库版本');
  }
  const toolRegistry = new ToolRegistry();
  const runtimeScriptPath = app.isPackaged
    ? path.join(process.resourcesPath, 'runtime', 'media_runtime.py')
    : path.join(app.getAppPath(), 'runtime', 'media_runtime.py');
  const executableSearchPath = [
    process.env.PATH,
    ...(process.platform === 'darwin'
      ? ['/opt/homebrew/bin', '/usr/local/bin', '/usr/bin', '/bin']
      : []),
  ].filter((value): value is string => Boolean(value)).join(path.delimiter);
  const mediaSuite = registerDeterministicMediaTools(
    toolRegistry,
    materialSessionSourceResolver(materialSessionService),
    {
      ffmpeg: { pathValue: executableSearchPath },
      learned: {
        asrModelPath: process.env.MATERIAL_ASR_MODEL_PATH,
        audioEventModelPath: process.env.MATERIAL_AUDIO_EVENT_MODEL_PATH,
        ocrLanguage: 'ch',
        ocrModelPath: process.env.MATERIAL_OCR_MODEL_PATH,
        pythonPath: process.env.MATERIAL_MEDIA_PYTHON,
        scriptPath: runtimeScriptPath,
      },
    },
  );
  const artifacts = new TemporaryArtifactManager(
    path.join(app.getPath('temp'), 'material-analysis-tools'),
  );
  void artifacts.sweepStale(24 * 60 * 60 * 1000).catch(() => undefined);
  const toolBroker = new ToolBroker(toolRegistry, artifacts, {
    allowedCapabilities: mediaSuite.snapshots.map((item) => item.capabilityId),
    allowedPermissions: ['material:read', 'process:spawn', 'temp:write'],
    maxConcurrentInvocations: 8,
    resourceCeilings: {
      maxArtifactBytes: 512 * 1024 * 1024,
      maxArtifacts: 40,
      maxOutputBytes: 32 * 1024 * 1024,
      timeoutMs: 20 * 60 * 1000,
    },
  });
  analysisRuntimeService = new AnalysisRuntimeService(
    toolBroker,
    materialSessionService,
    new AnalysisEngine(new CodexSubscriptionModelRouter(
      modelService,
      codexSubscriptionService,
    )),
    productRepository,
  );
  registerModelIpc(
    modelService,
    isTrustedSender,
  );
  unregisterCodexSubscriptionIpc = registerCodexSubscriptionIpc(
    codexSubscriptionService,
    isTrustedSender,
    (channel, payload) => {
      if (mainWindow && !mainWindow.isDestroyed() && !mainWindow.webContents.isDestroyed()) {
        mainWindow.webContents.send(channel, payload);
      }
    },
  );
  registerAnalysisRuntimeIpc(analysisRuntimeService, isTrustedSender);
  createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (!mainWindow || mainWindow.isDestroyed()) {
    createWindow();
  }
});

app.on('before-quit', () => {
  analysisRuntimeService?.cancelAll();
  analysisRuntimeService = null;
  unregisterCodexSubscriptionIpc?.();
  unregisterCodexSubscriptionIpc = null;
  codexSubscriptionService?.stop();
  codexSubscriptionService = null;
  materialSessionService.clear();
  productRepository?.close();
  productRepository = null;
  recordRepository?.close();
  recordRepository = null;
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
